"""Commit message

Revision ID: d182af7d7b6c
Revises: 6e688af52b7c
Create Date: 2020-09-23 16:41:14.635320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd182af7d7b6c'
down_revision = '6e688af52b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish_categories', 'name_uz')
    op.drop_column('dishes', 'name_uz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('name_uz', sa.VARCHAR(length=100), nullable=True))
    op.add_column('dish_categories', sa.Column('name_uz', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
